### ISSUE TITLE
articles yml does not control articles section dropdown menu

### ISSUE THREAD

**Issue by CrumpLab** [r-lib/pkgdown#1011]
This issue is similar to #995 and #325 

This minimal example shows what appears to be a problem the yml for controlling the dropdown navigation for articles.

The yml below should do the following, but it does not: 1) rename the "articles" tab, 2) write a line of text in the article dropdown tab, and 3) re-order the listed articles to show Article2 before Article1. Additionally, deleting one of the articles from the list under menu does not eliminate it from the dropdown navigation.

```
navbar:
  components:
    articles:
      text: New Name for Articles not showing
      menu:
      - text: This Text doesn't show
      - text: Article2
        href: articles/Article2.html
      - text: Article1
        href: articles/Article1.html
```

link to minimal example:

[https://github.com/CrumpLab/pkgdownMenuProblem](https://github.com/CrumpLab/pkgdownMenuProblem)

Many apologies if this has already been solved. I've attempted to read all of the issues and documentation, and still can't get it to work, so started to wonder if there was a bug, thanks for all the great work on pkgdown!
