### ISSUE TITLE
Building fails [ENOENT]

### ISSUE THREAD

**Issue by TheOnlyArtz** [r-lib/pkgdown#1108]
Hey! I have the next config:

```yaml
reference:
  - title: "Events"
    desc: >
      The events that will be emitted to the client
    contents:
      - ready
      - guildcreate
      - guildupdate
  - title: "Models/Types"
    desc: >
      The avilable data structures (S3 classes)
    contents:
      - Client
      - Channel
      - Emoji
      - Guild
      - GuildMember
      - Presence
      - User
  - title: "Gateway requests"
    desc: >
      Function that their purpose is to function through the gateway
    contents:
      - update.presence
```

When building:
![image](https://user-images.githubusercontent.com/30025874/62838787-5e4a9b80-bc89-11e9-93d0-ce09207fdd31.png)
