### ISSUE TITLE
Add affiliations option to authors

### ISSUE THREAD

**Issue by msberends** [r-lib/pkgdown#1130]
It would be great to have an option to include the affiliation of any package author and contributor. The `DESCRIPTION` file cannot contain this information, but a website can of course be more comprehensive in a lot of ways.

I would suggest to just add this to the already available `authors` field in `_pkgdown.yml`:

```yml
authors:
  Jane Doe:
    affiliation: "Faculty of Statistics and Tidyverse, Example University of Someplace, Someplace, Somewhere"
  John Doe:
    affiliation: "Faculty of R Cookbooks, Some University, Someplace, Somewhere"
```

This information could then be parsed for the `./authors.html` file.

For some package, [like ours](https://msberends.gitlab.io/AMR/index.html), it would be great if it could include doctoral titles or any other name prefix/suffix as well, as some packages are meant for academic research and this could be required by some university policies.

```yml
authors:
  Jane Doe:
    prefix: "Dr"
  John Doe:
    prefix: "Prof."
```

### Example how it is now:

Jane Doe. Author, maintainer.

John Doe. Author.

### Example with new affiliation:

**Jane Doe.** Author, maintainer. Faculty of Statistics and Tidyverse, Example University of Someplace, Someplace, Somewhere.

**John Doe.** Author. Faculty of R Cookbooks, Some University, Someplace, Somewhere.

### Example with new prefix:

Dr Jane Doe. Author, maintainer.

Prof. John Doe. Author.

### Example how this could be really awesome:

Dr Jane Doe<sup>1</sup>

Dr Jessa J. Doe<sup>1</sup>

Joanna J. Doe<sup>1</sup>

Prof. John Doe<sup>2</sup>

<sup>1</sup> Faculty of Statistics and Tidyverse, Example University of Someplace, Someplace, Somewhere.

<sup>2</sup> Faculty of R Cookbooks, Some University, Someplace, Somewhere.
