### ISSUE TITLE
pkgdown v1.4.0 adds href requirement for navbar

### ISSUE THREAD

**Issue by juniperlsimonis** [r-lib/pkgdown#1142]
in builds using v1.3.0, the `_pkgdown.yml` did not require the user to explicitly state `href` values for standard top-level menu components (like "reference") or explicitly state any sub components (such as specific vignettes) 

in builds with v1.4.0, the `_pkgdown.yml` file now requires the user to explicitly state `href` values and detail subcomponents, otherwise the content is rendered as text with a different formatting and no hyperlink.

a testing directory [here](https://github.com/dapperstats/test) has a working simple example. the most recent commit has a version that works under 1.3.0 but not under 1.4.0, as is evident from the [deployed site](https://dapperstats.github.io/test/) (built via travis).

i can reproduce this locally using `pkgdown::build_site()`:
![image](https://user-images.githubusercontent.com/23511502/64573891-e45a1080-d321-11e9-9b2a-be20c2a0410c.png)
![image](https://user-images.githubusercontent.com/23511502/64573895-e623d400-d321-11e9-97a1-b3d622bca1c3.png)
![image](https://user-images.githubusercontent.com/23511502/64573899-e9b75b00-d321-11e9-82da-6fa1a62e4f78.png)
![image](https://user-images.githubusercontent.com/23511502/64573900-ecb24b80-d321-11e9-9b78-bedafd6df78a.png)

the code that works with 1.3.0 but not 1.4.0:
```
url: https://dapperstats.github.io/test
development:
  mode: auto
navbar:
  structure:
    left: [home, reference]
  components:
    reference:
      text: "Functions"
```

to make it work under 1.4.0, all that was needed was to explicitly state the `href`
```
url: https://dapperstats.github.io/test
development:
  mode: auto
navbar:
  structure:
    left: [home, reference]
  components:
    reference:
      text: "Functions"
      href: reference/index.html
```

this behavior was observed in the wild first while working on the [portalcasting](https://github.com/weecology/portalcasting) package.
it manifested in a few additional ways that aren't reproduced explicitly in this toy example, but might be caused by the same underlying component(?):
1. it dropped the github icon link that was previously just mentioned in the `structure` component, because the github component wasn't explicitly called out.
2. it dropped the vignette menu because the menu wasn't explicitly built out.

[the version of the yml that worked on 1.3.0](https://github.com/weecology/portalcasting/blob/ac0774fb79a8bc3713c547a0cc4367e658cc6518/_pkgdown.yml)
[what it needed to be changed to to work on 1.4.0](https://github.com/weecology/portalcasting/blob/master/_pkgdown.yml)
