### ISSUE TITLE
allow customization of navbar articles order

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pkgdown#1146]
For `pkgdown` websites with a number of vignettes that might be logically ordered / grouped.

One simple solution: allow the navigation bar to be customized from within the `articles:` section; e.g. (copying from https://pkgdown.r-lib.org/reference/build_site.html)

```
articles:
  navbar:
    text: Articles
    menu:
    - text: Category A
    - text: Title A1
      href: articles/a1.html
    - text: Title A2
      href: articles/a2.html
    - text: -------
    - text: "Category B"
    - text: Title B1
      href: articles/b1.html
```

This would use the same format as for explicitly-defined navbars, but allow users to customize only this specific navbar as desired (leaving the rest as pkgdown default).

It could also be worth allowing short-form specifications of the vignettes, where the text is inferred from the title of the vignette used in a particular location. E.g. something like:

```
articles:
  navbar:
    text: Articles
    menu:
    - vignette: introduction
    - section: Collaborating
    - vignette: collaborating-a
    - vignette: collaborating-b
```

The main advantage of this approach is that it allows `pkgdown` websites to adapt to changes in the default navbar layout / display, if they change as newer versions of `pkgdown` are released.

**Comment by hadley** [comment]
Apparently we already support:

```yaml
articles:
- title: R Markdown
  contents:
  - starts_with("authoring")
- title: Websites
  contents:
  - rmarkdown_websites
  - rmarkdown_site_generators
```

So what if we also used that to generate navbar subtitles and set the default ordering?
