### ISSUE TITLE
Top-level release metadata

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1244]
Maybe something like:

```yaml
releases:
- version: "1.4.0"
  href: https://www.tidyverse.org/articles/2019/09/pkgdown-1-4-0/
- version: "1.3.0"
  href: https://www.tidyverse.org/articles/2018/12/pkgdown-1-3-0/
- version: "1.1.0"
  href: https://www.tidyverse.org/articles/2018/06/pkgdown-1-1-0/
- version: "1.0.0"
  href: https://www.tidyverse.org/articles/2018/05/pkgdown-1-0-0/
```

which would automatically generate

```yaml
navbar:
  components:
    news:
      text: News
      menu:
      - text: "Release notes"
      - text: "Version 1.4.0"
        href: https://www.tidyverse.org/articles/2019/09/pkgdown-1-4-0/
      - text: "Version 1.3.0"
        href: https://www.tidyverse.org/articles/2018/12/pkgdown-1-3-0/
      - text: "Version 1.1.0"
        href: https://www.tidyverse.org/articles/2018/06/pkgdown-1-1-0/
      - text: "Version 1.0.0"
        href: https://www.tidyverse.org/articles/2018/05/pkgdown-1-0-0/
      - text: "------------------"
      - text: "Change log"
        href: news/index.html
```
