### ISSUE TITLE
Allow topics from another R package

### ISSUE THREAD

**Issue by schloerke** [r-lib/pkgdown#1251]
Either by linking to their website or building locally.

Use case: reexports from other packages.

Examples:
* `shiny` reexporting [many methods from `htmltools`](https://github.com/rstudio/shiny/blob/cdafefc1f39548ad0be0bdbc46db32208ef2fb2c/R/reexport-htmltools.R)
* `dplyr` could display help docs about the [`tibble` methods it reexports](https://github.com/tidyverse/dplyr/blob/041bb5198adcb81b02d816b13b64dea81bafcf0f/R/reexport-tibble.r). 

Example api using local copies of man files...

```yml
reference:
  - title: Title here
    desc: Description here
    contents:
      - localFunction1
      - dplyr::filter
      - dplyr::arrange
      - localFunction2
```

Example api pointing to an external URL...

```yml
reference:
  - title: Title here
    desc: Description here
    contents:
      - localFunction1
      - filter:
        href:  https://dplyr.tidyverse.org/reference/filter.html
      - arrange:
        href: https://dplyr.tidyverse.org/reference/arrange.html
      - localFunction2
```
