### ISSUE TITLE
Allow to specify redirects in _pkgdown.yml

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/pkgdown#1259]
Assuming I have a vignette that I rename, the pkgdown link to this vignette will change and all people who follow the old link will see a 404 error. The same with help files for renamed functions etc. It would be nice if {pkgdown} could provide a way to specify redirects manually, relative to the base url, e.g. in `_pkgdown.yml`:

```yml
redirects:
  articles/new-vignette-name.html:
  - articles/old-vignette-name.html
  - articles/another-old-vignette-name.html
```

Looks like this is valid yml. The key should be the new name, because it's potentially a one-to-many mapping. What do you think of such a feature?
