### ISSUE TITLE
pkgdown::deploy_site_github reports git error on Travis-CI

### ISSUE THREAD

**Issue by FelixErnst** [r-lib/pkgdown#1274]
Hi,

I have a peculiar error, which is currently affecting my travis config.

This is the deploy config I am using
```
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY",""))'
  skip_cleanup: true
```

and this results in a git error "remote: Invalid username or password." for all repos I have tried so far. The error appeared yesterday for the first time. 

I tried to debug this on the Travis-CI system, but everthing seems to be in order. The ssh key get written correctly, but somehow this error appears during the last step, the `git push`. Running `pkgdown::deploy_site_github` locally works.

Do anyone can offer some advice how to debug this further? I already reset my travis deploy keys, no luck so far.

Felix

Link to the Travis-CI build: https://travis-ci.com/github/FelixErnst/Modstrings/builds/154396023
