### ISSUE TITLE
pkgdown does not recognize non-ASCII characters when deploying to Travis

### ISSUE THREAD

**Issue by kguidonimartins** [r-lib/pkgdown#1287]
We are trying to deploy our package [site](https://liibre.github.io/coronabr/index.html) using Travis with the 'UTF-8' encoding. When we build our site locally using `pkgdown::build_site()`, our *.md files (README, CONTRIB. AND ABOUT) are rendered correctly. However, when we deploy the site, pkgdown does not recognize non-ASCII characters from *.md files. The articles in the vignette folder are deployed with the correct encoding. We tried different solutions, for example, including a .Rprofile with `options(encoding = 'UTF-8')` via Makefile just for deployment, but it also doesn't work.

**Below is how our home page is rendered after deployment:**

![image](https://user-images.githubusercontent.com/8163542/78307213-cea97400-751b-11ea-8658-6651ae4397c1.png)

**And how our articles are rendered after deployment:**

![image](https://user-images.githubusercontent.com/8163542/78307232-d832dc00-751b-11ea-9525-56eb9c3d6483.png)

**Here is the travis.yml we are using:**

```yml
language: r

sudo: false

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-gnome-pt language-pack-pt-base
  - sudo apt-get -y install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libgdal-dev bwidget libgdal-dev libgdal1-dev libgeos-dev libgeos++-dev libgsl0-dev libproj-dev libspatialite-dev netcdf-bin libgmp3-dev libudunits2-dev cargo

cache: packages

script: make all

env:
    global:
        - LANG=pt_BR.UTF-8
        - LC_ALL=pt_BR.UTF-8

matrix:
  include:
  - r: devel
  - r: release
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
      local-dir: docs
      on:
        branch: master

after_success:
  - Rscript -e 'devtools::install()'

r_packages:
  - brazilmaps
  - dplyr
  - plyr
  - fs
  - ggplot2
  - glue
  - httr
  - janitor
  - jsonlite
  - magrittr
  - readr
  - rlang
  - rvest
  - sf
  - stringr
  - tidyr
  - tmap
  - xml2
  - gganimate
  - devtools
  - knitr
  - rgdal
  - gifski
  - pkgdown
  - webshot
  - rmarkdown
  - remotes

os:
  - linux
```

How can we make this work?
