### ISSUE TITLE
Upper case letters in TOC

### ISSUE THREAD

**Issue by fmmattioni** [r-lib/pkgdown#1302]
Of course, this is something very minor, but I am just wondering whether there are any settings I might be missing to control this.

I have noticed that the new TOC has only the first letter capitalized:

<img width="1440" alt="Screenshot 2020-04-13 at 20 24 05" src="https://user-images.githubusercontent.com/36630619/79148237-74cf6680-7dc5-11ea-9218-6c2eb402a525.png">

Problem: when I publish my pkgdown website my TOC only contains upper case letters:

<img width="1440" alt="Screenshot 2020-04-13 at 20 23 54" src="https://user-images.githubusercontent.com/36630619/79148301-8fa1db00-7dc5-11ea-8de5-4a75c5127545.png">

I created a repo as a reprex: https://github.com/fmmattioni/pkgdownreprex

Any thoughts?

**Comment by jayhesselberth** [comment]
The sandstone bootswatch theme is unique in its uppercase transformation of `.nav` elements (other themes like cosmo do not).

From https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/sandstone/bootstrap.css:

``` css
.navbar .nav > li > a {
  font-size: 11px;
  line-height: 22px;
  font-weight: 500;
  text-transform: uppercase;
}
```

**Comment by fmmattioni** [comment]
Oh that's amazing, @jayhesselberth! I didn't know that.. thank you very much for the quick reply!

**Comment by fmmattioni** [comment]
Just to add something here: the above solution was selecting the navigation bar at the top of the page instead of the `.nav` elements in the TOC.

The following solved it:

```css
nav[data-toggle='toc'] .nav > li > a {
  text-transform: none !important;
}
```
