### ISSUE TITLE
set default article yaml front matter in _pkgdown.yml

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#1313]
rmarkdown websites have this [handy feature](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html) where you can set the `output:` element for all `*.rmd` in the `_site.yml` like so:

```yaml
name: "my-website"
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
output:
  html_document:
    theme: cosmo
```

This is super handy because it keeps the individual `*.rmd` yaml front matter tight.

I understand that {pkgdown} is designed to work with it's own output template, though manually setting `output: bookdown::html_document2()` for each of the articles seems to work fine and adds support for bookdown features.

Anyway, I'd be great to add this feature to factor out the yamls.

**Comment by jayhesselberth** [comment]
I can't tell what you're advocating for. A `_site.yml` file that specifies styles for all vignettes? This is useful for bookdown, where you have lots of Rmd files, but seems less useful for pkgdown sites, which typically have only a few vignettes.

**Comment by maxheld83** [comment]
Sorry for being obtuse.
I was advocating for the ability to use this `_site.yml` feature inside of a `_pkgdown.yml` such as in the below. 

```
destination: docs
output:
  pdf_document: default
  html_document: default
```

But actually, perhaps a `_site.yml` or something like that inside `vignettes/` actually makes more sense, since the `output:` keyword should never affect the rest of the pkgdown site, and it would be confusing to have it in the `_pkgdown.yml`.

We *do* have quite a number of vignettes in some packages and we sometimes specify multiple output formats, as when a vignette is also rendered to PDF according to some journal spec.
