### ISSUE TITLE
link previews for vignettes within articles

### ISSUE THREAD

**Issue by donaldRwilliams** [r-lib/pkgdown#1328]
I have a question about link previews when sharing on twitter (for example).

I have noted that I get `INFO:  Card loaded successfully` for 

https://donaldrwilliams.github.io/BGGM/articles/

which then displays the package logo, etc.

However, when sharing files within articles, e.g., 

https://donaldrwilliams.github.io/BGGM/articles/mcmc_diagnostics.html

I get `ERROR: No card found (Card error)`.

I have checked and this seems to apply to all the sections.

Here is the `_pkgdown.yml` file

```
title: BGGM
url: https://donaldrwilliams.github.io/BGGM/
template:
  params:
    bootswatch: flatly
  opengraph:
    image:
      src: man/figures/hex.jpg
    twitter:
      creator: "@wdonald_1985"
      card: summary

```

Anyhow, I am wondering how to get link previews for the individual vignettes (no need for page specific images, etc., just some preview would be ideal)
