### ISSUE TITLE
ignored articles end up in docs/pkgdown.yml

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#1340]
as per [the docs](https://pkgdown.r-lib.org/reference/build_articles.html):

> Files that start with _ (e.g., _index.Rmd) are ignored.

However, `touch vignettes/_foo.Rmd` and running `pkgdown::render_site()` *does* yield this `docs/pkgdown.yml`:

```yaml
pandoc: 2.9.2.1
pkgdown: 1.5.1
pkgdown_sha: ~
articles:
  _foo: _foo.html
  about: about.html
  interactive: interactive.html
last_built: 2020-06-02T16:00Z
```

I'm not sure who/what is using the *rendered* `docs/pkgdown.yml`, but it seems odd and potentially buggy to include `_foo.html` here, which is a path that rightfully does *not* exist and is *not* actually an article.

(I'm also having trouble getting a pkgdown page indexed by docsearch, and am currently guessing that this might have something to do with the problem, but that's entirely speculative as per https://github.com/subugoe/hoad/issues/82).
