### ISSUE TITLE
everything() helper for including missing references

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/pkgdown#1350]
I'm building my `_pkgdown.yml` file and I think it would be great to be able to include all missing references with some helper, such as `everything()`.

I would like to be able to write something like this:

```yaml
reference:
- title: "Main functions"
  desc: "I really have something to say about these 2."
- contents: 
  - fun1
  - fun2
- title: "Misc"
  desc: "Other minor functions"
- contents:
  - everything()
```

There is a 2 years old SO question about that [here](https://stackoverflow.com/questions/45886789/include-all-other-functions-in-a-pkgdown-reference-yaml), but the solution is not that simple.

I'm a bit surprised that I couldn't find this mentioned anywhere, sorry for the inconvenience if my research was incomplete and this is a duplicate.
