### ISSUE TITLE
Relative links on 404 page

### ISSUE THREAD

**Issue by ms609** [r-lib/pkgdown#1356]
I have specified relative links in my `_pkgdown.yml`, for example:

```yml
navbar:
  components:
    get-started:
      text: Get started
      href: articles/Using-this-package.html
```
Where necessary 'pkgdown' seems to cleverly adapt these links by adding a `../` prefix, so that links do not become `.../articles/articles/...`. 

But this doesn't seem to be the case on the '404' page: [`https://me.github.io/my-package/articles/Nothing-here.html`](https://ms609.github.io/TreeDist/articles/Nothing-here.html) gives the helpful 404 message "use the links in the navbar", but these links contain an extra `articles` so do not themselves work.

One possible solution might be to use the entry in the `url:` yaml field to write the links on the 404 page?
