### ISSUE TITLE
Articles submenu is added even when disabled in the yaml file.

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/pkgdown#1375]
I have a package where a vignettes directory is present. The yaml file contains

```
destination: site
navbar:
  structure:
    left:  [home, intro, reference, news]
    right: []
articles:
```

I also build with the following process:

Rscript -e 'pkg <- "."; pkgdown::init_site(pkg); pkgdown::build_home(pkg); pkgdown::build_reference(pkg, examples=FALSE); pkgdown::build_news(pkg)'

to prevent execution of vignettes. Regardless, the Menu will contain an "Articles" section with no entries in the menu (the dropdown is not even present).

I expect the Articles menu entry should not be present.

**Comment by hadley** [comment]
`structure` only defines the location of the components that are present. You want:

```yaml
navbar:
  components:
    articles: ~
```
