### ISSUE TITLE
Feature request: Additional sidebar entries

### ISSUE THREAD

**Issue by jakob-wirbel** [r-lib/pkgdown#1443]
Hi all 👋 
thanks for the amazing package, first of all! :)
I was just wondering if it would be possible to create custom entries into the sidebar. As far as i have understood, you can create a section called "Links" by entering them into the `_pkgdown.yml`:
```
home:
  links:
  - text: Check out the the source code
    href: https://github.com/your_awesome_project
```

However, I also wanted to include funding sources on the website and thought it should be possible to include other, custom sections into the sidebar.
I tried
```
home:
  links:
  - text: Check out the the source code
    href: https://github.com/your_awesome_project
  funding:
  - text: We are grateful for funding through the ministry for education and research
```

Also, is it possible to include images in the sidebar using the same syntax?

Thanks!

**Comment by maelle** [comment]
Here's how one would add a funding component.

```yaml
home:
  sidebar:
   structure: [links, license, community, citation, authors, funding, dev]
   components:
     funding:
       title: Funding
       html: We are grateful for funding through the ministry for education and research.
```
