### ISSUE TITLE
deploy_to_branch() only fetch git lfs files when the gh-pages branch does not exist

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1454]
I have a repository with files stored with git lfs: https://github.com/bisaloo/NpiEurope_compendium.

The first time I run the pkgdown GitHub Action, it created the gh-pages branch and everything worked fine.

Each subsequent run failed because it does not fetch the data stored with git lfs anymore.

I checked this is indeed this issue by deleting the gh-pages branch and triggering a new run of the GitHub action.

**Comment by Bisaloo** [comment]
In case others come across this issue, the fix is to edit this line in the `pkgdown.yaml` file:

```yml
    steps:
      - uses: actions/checkout@v2
```

to 

```yml
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: 'true'
```
