### ISSUE TITLE
References in vignettes: spacing issue

### ISSUE THREAD

**Issue by aaamini** [r-lib/pkgdown#1469]
I have written a vignette that is rendered as an article by `pkgdown`. The vignette has some references. When rendering it as an html in Rstudio, using the Knit button, the references are rendered as follows:
![Screenshot from 2021-01-20 20-23-34](https://user-images.githubusercontent.com/17173393/105280269-3b9b0280-5b5e-11eb-88ae-843dc33c01a3.png)
with a proper justification of the second lines so that the references are easily distinguishable. When rendered with `pkgdown` however the spaces in front of the second line of each reference are gone as can be seen on the [deployed website](https://aaamini.github.io/nett/articles/hard_dcsbm_testing.html#references).

Is there a fix to get the proper spacing in the rendered site?

**Comment by jayhesselberth** [comment]
You could add the following to `pkgdown/extra.css`:

```css
div.csl-entry {
  text-indent: -2em;
  padding-left: 2em;
}
```

**Comment by aaamini** [comment]
@jayhesselberth Thanks. Is there a command that I can run that `docs/extra.css` based on `pkgdown/extra.css` without rebuilding the whole site. I am hoping that I can avoid rebuilding the costly articles.

**Comment by jayhesselberth** [comment]
pkgdown adds a new line to each head referencing `extra.css`.

You could run `init_site()`, `build_home()`, and `build_reference()` to re-build only those components, but you'd have to add the new head content to articles by hand.

**Comment by aaamini** [comment]
Thanks. I had, sort of, figured out that idea, as a cheap adhoc way of updating and was wondering if that is what I am supposed to be doing. I also noticed that the heads do not get updated on articles, etc. (e.g., the version does not get updated on these pages and so on). It seems that it would be a nice feature to provide a command that automatically does all that and updates the heads on all pages, without the need to generate the time-consuming body of articles.

**Comment by maxheld83** [comment]
There was a similar issue over at https://github.com/rstudio/rmarkdown/issues/1959, closed in https://github.com/rstudio/rmarkdown/pull/1960.

Would there be any interest in adding that CSS to pkgdown?

I got it to look pretty ok with this `extra.css` (though this omits some of the pandoc vars):

```css
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
```

Happy to make a PR if this is welcome in pkgdown (and if you could give me a pointer *where*).
