### ISSUE TITLE
Twitter card image src must be URL, not absolute path

### ISSUE THREAD

**Issue by dcnorris** [r-lib/pkgdown#1685]
Apparently, Twitter card images cannot be SVGs, and cannot be relative paths:
https://twittercommunity.com/t/card-error-unable-to-render-or-no-image-read-this-first/62736

The [Metadata article](https://pkgdown.r-lib.org/articles/metadata.html) seemed to me to suggest otherwise.
After many tries with a relative img path in `_pkgdown.yml` I have been able successfully to get the card image for package [precautionary](https://dcnorris.github.io/precautionary/index.html) by giving a URL pointing to a png in my repo:

```
template:
  opengraph:
    image:
      src: https://github.com/dcnorris/precautionary/raw/main/docs/card.png
      alt: "Logo for precautionary package"
    twitter:
      creator: "@davidcnorrismd"
      card: summary
```

I imagine referring to something in `raw/main/` is not an ideal approach, but would be glad for more guidance in the Metadata article.
