### ISSUE TITLE
Switch to bs4_book link styling for consistency

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1686]
i.e.

```css
code a:any-link {
  color: inherit;
  text-decoration: underline;
  text-decoration-color: $table-border-color;
}
```
