### ISSUE TITLE
Thinking about dark mode

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1696]
There will be two CSS files, one light and one dark.

I am wondering how users could provide variables especially for dark mode (bslib-dark in YAML?).

```yaml
bslib:
  variable1: bla
  variable2: blabla
bslib-dark:
  variable1: blop
```

now what should be the value for variable2 in dark mode: the Bootstrap/pkgdown default, or variable2 as defined under `bslib:`?

The former seems more logical if this variable is a colour, but if it's a font for instance, it would be a bit annoying to define it twice.
