### ISSUE TITLE
New `<code>` block inside `<pre>` wraps code on small screens

### ISSUE THREAD

**Issue by msberends** [r-lib/pkgdown#1743]
The current NEWS file states:

> * pkgdown (in concert with downlit and roxygen2) is moving towards more consistent HTML structure for syntax highlighting. The goal is to always have a `<div>` with class `sourceCode` (and other classes as needed), which contains one or more `<pre>`s that has class `sourceCode` and the language, and each `<pre>` contains `<code>`.

Especially this last part (`<code>` inside `<pre>`) has a strange effect on smaller screens:

OLD BEHAVIOUR

<img width="531" alt="image" src="https://user-images.githubusercontent.com/31037261/127749538-decf0b9f-6a71-42f1-9dbc-8546fec3d63d.png">

CURRENT BEHAVIOUR

<img width="520" alt="image" src="https://user-images.githubusercontent.com/31037261/127749561-63b211ee-8f4a-4dcb-b16f-e6332185fa5d.png">

The problem is this:

```css
pre, pre code {
  background-color: #f8f8f8;
  color: #333;
  white-space: pre-wrap;
  word-break: break-all;
  overflow-wrap: break-word;
}
```

Since `code` should not have this word-wrap and white-space, but rather:

```css
pre code {
  word-wrap: normal;
  white-space: pre;
}
```

Adding these last four lines to `extra.css` fixes the work-breaking for me.
