### ISSUE TITLE
Function for building for github pages

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1756]
```R
build_site_github_pages <- function(pkg = ".", clean = TRUE) {
 pkg <- as_pkgdown(pkg, override = list(destination = dest_dir))

  if (clean) {
    rule("Cleaning files from old site", line = 1)
    clean_site(pkg)
  }

  build_site(pkg, devel = FALSE, preview = FALSE, install = FALSE, ...)
  build_github_pages(pkg)
  
  invisible()
}
```

Then we could refactor our [standard action](https://github.com/r-lib/actions/blob/master/examples/pkgdown-pak.yaml) to build and then deploy. So instead of:

```yaml
     - name: Build and deploy pkgdown site
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
```

We'd have something like:

```yaml
      - name: Build pkgdown site
        run: pkgdown::build_site_github_pages()
        shell: Rscript {0}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: docs
```
