### ISSUE TITLE
Document _output.yml rather than _site.yml for vignette output format

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1764]
Since #1313 the docs mention one can use `_site.yml`.

However @cderv explained to me that it's more logical and simple to use `_output.yml`. Logical because the site config is for websites, and simple because you can omit the "output" key.

E.g. `_output.yml` can be

```yaml
html_document:
  toc: true
  toc_float: true
  number_sections: false
  theme: flatly
```
