### ISSUE TITLE
BS4: `pre` img stretched

### ISSUE THREAD

**Issue by dieghernan** [r-lib/pkgdown#1790]
Hi:

When building my site with the BS4 version, I noticed that plots generated on the examples looks stretched on mobile phones:

![image](https://user-images.githubusercontent.com/25656809/134762708-7a5b63c1-c3bd-44ea-a39a-2c16a0960ea0.jpeg)

I think this is due to a missing css rule on `pkgdown.css`. I added a custom css rule to my template .css file and it seems to be fixed:

```css

/* pkgdown hack */

pre .r-plt img {
  background-color: #fff;
  margin: 5px 0;
  display: block;
  height: auto;
}

```

<details>

Result 

![image](https://user-images.githubusercontent.com/25656809/134762788-b8a32ad3-2cbb-41d7-8eb8-f7228b12d2a7.jpeg)

Template repo: https://github.com/ropengov/rogtemplate, https://ropengov.github.io/rogtemplate/

</details>
