### ISSUE TITLE
Footer structure should match navbar

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1824]
```yaml
footer:
 left:
   structure: [pkgdown]
 right:
   structure: [authors, legal]
   components:
     legal: Provided without ***any warranty***.
```

->

```yaml
footer:
  structure:
    left: [pkgdown]
    right: [authors, legal]
 components:
    legal: Provided without ***any warranty***.
```
