### ISSUE TITLE
Gallery of articles, examples, etc.

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pkgdown#1899]
## Overview

This issue is to lay out my thoughts about a gallery feature for pkgdown sites. The goal is to make facilitate pages similar to the existing [learnr](https://ojgs.rstudio.com/learnr/examples.html) and [flexdashboard](https://pkgs.rstudio.com/flexdashboard/articles/examples.html) examples pages.

The gallery I envision would require BS5 and would use Bootstrap's [cards component](https://getbootstrap.com/docs/5.0/components/card/). If a link is provided, the card image and title would be a clickable link.

![image](https://user-images.githubusercontent.com/5420529/141202996-b2cca4fd-7ba6-4e61-846e-fa8685ad8611.png)

## Data Structure

At its core, the gallery would be created with a YAML list:

```yaml
- title: "Setting Up R"
  image: images/tutorial-ex-setup-r.png
  link: https://learnr-examples.shinyapps.io/ex-setup-r/
  footer:
    structure: [source]
    components: 
      source: https://github.com/rstudio/learnr/tree/master/inst/tutorials/ex-setup-r/ex-setup-r.Rmd
  description: >
    A tutorial featuring videos and interactive questions to guide a new **R** user
    through the installation and set up of everything they'll need to get
    started with **R**.
```

## API

The primary question I'm facing is how a user would instantiate a gallery. Here are a few options I've thought of, but I'd love to hear your thoughts on the user-facing API.

### With an R function

One option would be to call a function exported by pkgdown, that would read the data from this file (or optionally would accept an R list):

````markdown
```{r gallery, echo=FALSE}
pkgdown::gallery("examples.yml")
```
````

The advantage is that this function is portable and its usage is straightforward, but I have two hesitations:

1. The function needs to ensure that BS5 is in use, so we'd have to either find the root DESCRIPTION file or ask that users include that as an argument. If the gallery were powered by functions called by `build_article()`, we could handle this internally.

2. Furthermore, pkgdown functions don't tend to make appearances in source code. All other exported functions are intended to be called interactively, but this one would start to appear in source code.

### In the YAML front matter

Another option would be to put the gallery items in the YAML front matter as a named list of galleries and then insert the gallery with basic HTML or a special string (here are some brain-storming options)

```markdown
---
gallery:
  examples:
    - title: "Setting Up R"
      image: images/tutorial-ex-setup-r.png
      link: https://learnr-examples.shinyapps.io/ex-setup-r/
---

<div class="gallery" id="examples"></div>

[]{.gallery #examples}

<!--gallery: examples -->

<gallery id="examples">
```

This above YAML structure for `example` might not be sufficient, we might have to have a very nested yaml list if we allow the gallery to have some options like number of columns or matching height rows.

Some advantages of this method are that we know everything we need to know at build time.

### In a `gallery` chunk

Another option I've considered would be to introduce a `gallery` knitr engine that takes YAML and inserts the HTML as needed. We'd install the knitr engine in the pkgdown article format that could even implement different versions for BS5 and BS3 (if we want). We could use chunk options to set options specifically for individual galleries.

````markdown
```{gallery ncol=3}
- title: "Setting Up R"
  image: images/tutorial-ex-setup-r.png
  link: https://learnr-examples.shinyapps.io/ex-setup-r/

- title: "Filtering Observations"
  image: images/tutorial-ex-data-filter.png
  link: https://learnr-examples.shinyapps.io/ex-data-filter/
```
````

**Comment by hadley** [comment]
What if the yaml lived `_pkgdown.yml` and generated some top-level "gallery" item in the navbar?

**Comment by gadenbuie** [comment]
> What if the yaml lived `_pkgdown.yml` and generated some top-level "gallery" item in the navbar?

I like this idea if the desired feature is a single "Gallery" page. While I think having one page would be a reasonable compromise for most users of pkgdown, I was envisioning a solution that allows a little more flexibility.

In the learnr docs, for example, a small gallery appears [on the home page](https://rstudio.github.io/learnr/) with a more complete gallery [in the Examples page](https://rstudio.github.io/learnr/examples.html). Personally I feel that it'd be better to break up learnr's examples page into two categories — complete example tutorials and tutorials that demonstrate learnr features — and I imagine that letting authors add some structure and text to galleries would improve overall documentation quality. For instance, I like that the [Shiny Gallery](https://shiny.rstudio.com/gallery/) divides the gallery into sections by industry in addition to example type.

Another option that has started to grow on me is that maybe we should leave this feature for a third-party package, like [bs4cards](https://bs4cards.djnavarro.net). This approach would pair nicely with #1896, which gives article authors a bit more room for custom layouts in the article format.

**Comment by hadley** [comment]
Yeah, relying on a external package might be cleaner; then it would make sense to take as a strong dependency and you can just call the functions in your article etc. 

Still might be nice to opt-in to an article or tutorial index that was a gallery inside of a list of articles. But that could just be a boolean flag in the `_pkgdown.yml` (assuming you set the desired images with the opengraph metadata).

**Comment by hadley** [comment]
@gadenbuie what if instead of using YAML we used an R data structure? And instead of using a special quarto template, we just provided some code that you could call to generate the cards in an article? Something like this:

```R
cards <- list(
  list(
    title = "Setting Up R",
    image = "images/tutorial-ex-setup-r.png",
    link = "https://learnr-examples.shinyapps.io/ex-setup-r/"
  )
)

pkgdown::render_gallery(cards)
```

Then you'd just use regular articles and customise their placement in the navbar.

**Comment by gadenbuie** [comment]
> * what if instead of using YAML we used an R data structure? And ... we just provided some code that you could call to generate the cards in an article?

I like it and it does sound considerably less complicated. For online-only articles, this is certainly uncomplicated. 

For vignettes, would authors be able to hide the `pkgdown::render_gallery()` call from CRAN? The docs could include the boilerplate chunk option to only run the code when `IN_PKGDOWN` is set, but would the presence of `pkgdown::render_gallery()` cause issues?

**Comment by hadley** [comment]
@gadenbuie I think if you wanted to include it in a vignette you'd need to add pkgdown to suggests. That's not ideal as pkgdown is a rather heavy dep, but it's not the end of the world.

**Comment by hadley** [comment]
Some initial exploration at https://github.com/rstudio/learnr/pull/815

**Comment by hadley** [comment]
Given that the R code is now quite simple (and maybe we could make it even simpler by including a helper in bslib?) I'm inclined to move back towards a simpler yaml based approach, allowing a site to add an optional `gallery` field to `_pkgdown.yml`. The structure would be a fusion of the existing learnr/flexdashboard yaml with the articles/references section structure so that you'd write something like this:

```yaml
- title: Complete Tutorials
  desc: >
    These tutorials were designed to showcase the features of the learnr 
    package --- and to teach learners how to use R! Try working through these 
    tutorials to get a sense of the look and feel of a learnr tutorial.
    Then check out the source code to see how these tutorials were made!

  contents:
  - title: Setting Up R
    image: images/tutorial-ex-setup-r.png
    link: https://learnr-examples.shinyapps.io/ex-setup-r/
    alt: Screenshot of a shiny app
    footer: [Source](https://github.com/rstudio/learnr/tree/main/inst/tutorials/ex-setup-r/ex-setup-r.Rmd)
    text: >
      A tutorial featuring videos and interactive questions to guide a new R user
      through the installation and set up of everything they'll need to get
      started with R.
```

Need to think about where the images would live.
