### ISSUE TITLE
Add link in custom Sidebar section?

### ISSUE THREAD

**Issue by samuel-marsh** [r-lib/pkgdown#1946]
Hi,

Apologies again if this is something simple that I'm missing but not sure.  Following the vignette (https://pkgdown.r-lib.org/articles/customise.html#sidebar) I'm customizing the sidebar of my site with a custom section.
i.e.,

```
home:
  sidebar:
    structure: [authors, custom, toc, dev]
    components:
      custom:
        title: Funding
        text: We are *grateful* for funding!
```

However, I've been trying to create a hyperlink in the text though via:

```
home:
  sidebar:
    structure: [authors, custom, toc, dev]
    components:
      custom:
        title: Funding
        text: We are *grateful* for funding!
        href: LINK_ADDRESS or articles/FAQ.hmtl
```

But that simply renders as the text field with no link.  Is it possible to make hyperlink in custom field and if so could you clarify how to do so?

Thanks!
Sam

**Comment by maelle** [comment]
Can you try

```
home:
  sidebar:
    structure: [authors, custom, toc, dev]
    components:
      custom:
        title: Funding
        text: [We are *grateful* for funding!](link)
```

**Comment by samuel-marsh** [comment]
Hi @maelle,

That works!  Thanks so much!!! :)

Best,
Sam

**Comment by telphick** [comment]
Hi @maelle ,

Is it possible to have a few rows under custom? Currently tried this but no luck.
```
home:
  sidebar:
    structure: [custom, authors, dev]
    components:
      custom:
        - title: General Information
          - text: "[Repository1](link)"
          - text: "[Repository2](link)"
        - title: Dashboards
          text: "[Dashboard](link)"
```
Kind regards,
Tiana
