### ISSUE TITLE
How to specify path in `_pkgdown.yml`'s `html` parameter

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#1996]
For a minimal reprex, see this package website: https://indrajeetpatil.github.io/minimalReprex/

The logo is rendered correctly in the footer only on the [homepage](https://indrajeetpatil.github.io/minimalReprex/):

![image](https://user-images.githubusercontent.com/11330453/148369928-856eac0d-eaae-44eb-b515-75c4c0182c08.png)

But not on any other [page](https://indrajeetpatil.github.io/minimalReprex/reference/index.html):

![image](https://user-images.githubusercontent.com/11330453/148369998-c86fa634-b4ed-4541-b067-3f5eae745af8.png)

I understand that anywhere other than `index.html`, this relative path `reference/figures/hu.png` fails, and that's what creates this issue. But I am not sure what the alternative way of specifying this path in `_pkgdown.yaml` is so that the funder logo will be available across all pages:

```yaml
authors:
  Harvard University:
    href: "Harvard University"
    html: "<img src='reference/figures/hu.png' height=24>"
```

P.S. I also checked out `{tidytemplate}`, since RStudio logo is rendered successfully across all pages of respective websites, but its [yaml](https://github.com/tidyverse/tidytemplate/blob/main/_pkgdown.yml) didn't provide any clues.

**Comment by IndrajeetPatil** [comment]
I understand that anywhere other than `index.html`, this relative path `reference/figures/hu.png` fails, but I am not sure what the alternative way of specifying this path in `_pkgdown.yaml` is so that it will be available throughout the website:

```yaml
authors:
  Harvard University:
    href: "Harvard University"
    html: "<img src='reference/figures/hu.png' height=24>"
```

**Comment by hadley** [comment]
It's currently hard coded (https://github.com/r-lib/pkgdown/blob/main/R/build-home-authors.R#L57-L60) (will be removed in #1952); the key is to use an absolute url.

**Comment by IndrajeetPatil** [comment]
Absolute URL did the trick, thanks!

```yaml
authors:
  Harvard University:
    href: "Harvard University"
    html: "<img src='https://indrajeetpatil.github.io/minimalReprex/reference/figures/hu.png' height=24>"
```
