### ISSUE TITLE
Add robustness to repo source not having a slash

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2017]
In https://github.com/r-lib/pkgdown/blob/6a412e3a9d2d12d43e6b24eb25b97633ec350cda/R/repo.R#L25 if one has e.g.

```yml
repo:
  url:
    home: https://gitlab.com/chuxinyuan/ecce
    source: https://gitlab.com/chuxinyuan/ecce/-/tree/master
```

without "/" the links to code source are wrong as they are, well, missing a slash.

Sort of related to #2015
