### ISSUE TITLE
Allow for external links in articles page

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/pkgdown#2028]
In [recipes](https://recipes.tidymodels.org/), we have a couple of articles that got moved away from the package itself to other sites. It would be nice if we could link externally from the articles page.

Below is an old `yaml` section that can't be updated to bs5

```yaml
  - text: "Articles"
    menu:
      - text: "Selecting Variables"
        href: articles/Selecting_Variables.html
      - text: "Custom Steps"
        href: https://www.tidymodels.org/learn/develop/recipes/
      - text: "The Order of Steps"
        href: articles/Ordering.html
      - text: "Dummy Variables and Interactions"
        href: articles/Dummies.html
      - text: "Column Roles"
        href: articles/Roles.html
      - text: "On Skipping Steps"
        href: articles/Skipping.html
      - text: "Subsampling for Class Imbalances"
        href: https://www.tidymodels.org/learn/models/sub-sampling/
      - text: "Multivariate Analysis using Partial Least Squares"
        href: https://www.tidymodels.org/learn/models/pls/
```

Below is what would be nice if it was possible (imaginary syntax)

```yaml
articles:
- title: About recipe Steps
  navbar: ~
  contents:
  - Selecting_Variables
  - Ordering
  - Dummies
  - Roles
  - Skipping
- title: Developer
  contents:
  - text: Custom Steps
    desc: Write a new recipe step for data preprocessing.
    href: https://www.tidymodels.org/learn/develop/recipes/
- title: Examples
  contents:
  - text: Subsampling for Class Imbalances
    desc: Improve model performance in imbalanced data sets through undersampling or oversampling.
    href: https://www.tidymodels.org/learn/models/sub-sampling/
  - text: Multivariate Analysis using Partial Least Squares
    desc: Build and fit a predictive model with more than one outcome.
    href: https://www.tidymodels.org/learn/models/pls/
```
