### ISSUE TITLE
Permit use of highlight.js themese

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/pkgdown#2058]
Presently the syntax highlighting is limited to the styles defined at https://github.com/r-lib/pkgdown/tree/main/inst/highlight-styles.

It would be nice to be able to specify a [highlight.js](https://highlightjs.org/static/demo/) theme in the `_pkgdown.yml` file. 

I've tried adding it as an include via `in_header:` with the stylesheet link to no avail.

Perhaps there are other work around that I am unfamiliar with, but this would be a very nice addition.

For example I can imagine syntax looking like: 

```
template:
  bootstrap: 5
  bootswatch: cyborg
  highlight_js_theme: atelier-estuary-light
```
