### ISSUE TITLE
Add possibility to add contents that are missing from previous reference sections

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/pkgdown#2090]
At the moment, if you enable the reference: section, you are forced to curate the list completely manually. As far as I could see, there's no way to say "everything that has not been matched previously" so I can have an "other" section with everything else. Example:

```
reference:
- title: Object Constructors
  desc: Functions to create objects
  contents:
  - foo
  - bar

- title: Other
  desc: Other functions
  contents:
  - matches(".*")
```

using matches with the regexp will create indeed such section with everything, but foo and bar will appear both in the Object Constructor sections and in the Other sections.

What is needed is a function equivalent to matches() that matches every function that has not been selected previously, like `unmatched()` or something like that.
