### ISSUE TITLE
Site no longer compiling with 2.0.4 and `has_concept`

### ISSUE THREAD

**Issue by tyluRp** [r-lib/pkgdown#2126]
I noticed that my github action started failing when I introduced `has_concept` in my `_pkgdown.yml` file to organize my reference page. I installed `pkgdown` 2.0.3 and the error went away. My `pkgdown` config and CI logs below:

* https://github.com/tyluRp/strava/blob/main/_pkgdown.yml
* https://github.com/tyluRp/strava/runs/6865590317?check_suite_focus=true

I also noticed that 2.0.4 introduced some additional checks on this file. Has me wondering, am I not using `has_concepts` correctly?

**Comment by dmurdoch** [comment]
I think you've got it right, but there's an issue here: https://github.com/r-lib/pkgdown/blob/7d7ebff95f580b70c3d955ba726871d60f3d81a8/R/topics.R#L186

The list of columns should include `"concepts"`; if you add it, the problem is fixed.

**Comment by tyluRp** [comment]
Good catch! For the time being, I am just going to install 2.0.3 until this is resolved: https://github.com/tyluRp/strava/blob/main/.github/workflows/pkgdown.yaml#L36-L38

**Comment by hadley** [comment]
Thanks for reporting — I'll try and get another release out ASAP.

**Comment by AARON-CLARK** [comment]
I can confirm that `has_keyword()` is also borked.

**Comment by mpadge** [comment]
Until 2.0.4 appears on CRAN, temp workaround for doc build fails on GitHub is to change pkgdown.yaml to use dev instead of CRAN version:
``` yaml
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          #extra-packages: any::pkgdown, local::.
          extra-packages: github::r-lib/pkgdown, local::.
```
