### ISSUE TITLE
Document and test cross-package doc linking

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2151]
From: https://github.com/r-lib/pkgdown/issues/715

Surprisingly this works for cross-package documentation

```yaml
...
- title: Visualization & Display
  desc: Graphics functions and print formats
  contents:
  - tf::plot.tf
  - geom_spaghetti
  - gglasagna
  - geom_capellini
  - tf::print.tf
  - type_sum.tf
....  
```
