### ISSUE TITLE
Topics marked internal in `_pkgdown.yml` still show up

### ISSUE THREAD

**Issue by markfairbanks** [r-lib/pkgdown#2174]
Topics marked internal in `_pkgdown.yml` still show up in the reference index. Note that the title "internal" doesn't show up, but the contents still do. 

https://github.com/markfairbanks/tidytable/blob/main/pkgdown/_pkgdown.yml

https://markfairbanks.github.io/tidytable/reference/index.html

I might just be misunderstanding the docs - but from what I was reading I didn't need to add `@keyword internal` to the functions, all that was needed was adjusting the `.yml` file.

Relevant section of `_pkgdown.yml` (at the bottom):
```
- title: internal
- contents:
  - arrange_across.
  - mutate_across.
  - summarize_across.
  - case.
  - get_dummies.
  - ifelse.
  - inv_gc
  - top_n.
```

**Comment by maelle** [comment]
This YAML excerpt should be 

```yaml
- title: internal
  contents:
  - arrange_across.
  - mutate_across.
  - summarize_across.
  - case.
  - get_dummies.
  - ifelse.
  - inv_gc
  - top_n.
```

without an hyphen before `contents:`. 

Example https://github.com/jsilve24/fido/blob/260856dbbe1d718eb2f5d4eb185e9580295fe7d4/_pkgdown.yml#L116 rendered to https://jsilve24.github.io/fido/reference/index.html
