### ISSUE TITLE
Cross-package auto-linking not working as expected

### ISSUE THREAD

**Issue by nicolerg** [r-lib/pkgdown#2203]
Thank you for developing this incredible resource! 

I have references between two R packages that are not creating links to where I'd expect. The packages are [MotrpacRatTraining6mo](https://motrpac.github.io/MotrpacRatTraining6mo/) and [MotrpacRatTraining6moData](https://motrpac.github.io/MotrpacRatTraining6moData/). 

For reasons [unknown to me](https://github.com/rdrr-io/rdrr-issues/issues/103), their documentation is not yet hosted on https://rdrr.io/, which looks like the default when `pkgdown` can't find a `pkgdown` site. However, both of these packages have `pkgdown` sites (links above), and I followed the guidance [here](https://pkgdown.r-lib.org/articles/linking.html#across-packages) to add the `pkgdown` site URL to `DESCRIPTION` and `_pkgdown.yml`. I hoped this would make the auto-links point to the docs on the `pkgdown` site instead of the nonexistent rdrr.io site, but all of the cross-package links still point to rdrr.io. How can I fix this?

Here's an example. 
I believe [MotrpacRatTraining6moData  docs/pkgdown.yml](https://github.com/MoTrPAC/MotrpacRatTraining6moData/blob/main/docs/pkgdown.yml) looks as expected:
```yml
pandoc: '2.18'
pkgdown: 2.0.6
pkgdown_sha: ~
articles:
  MotrpacRatTraining6moData: MotrpacRatTraining6moData.html
last_built: 2022-10-03T22:14Z
urls:
  reference: https://motrpac.github.io/MotrpacRatTraining6moData/reference
  article: https://motrpac.github.io/MotrpacRatTraining6moData/articles
```
But all links to `MotrpacRatTraining6moData` objects in the `MotrpacRatTraining6mo` docs still point to https://rdrr.io/pkg/MotrpacRatTraining6moData/. For example, see the link to `MotrpacRatTraining6moData::TISSUE_ABBREV` [here](https://motrpac.github.io/MotrpacRatTraining6mo/reference/combine_normalized_data.html). It points to https://rdrr.io/pkg/MotrpacRatTraining6moData/man/TISSUE_ABBREV.html instead of https://motrpac.github.io/MotrpacRatTraining6moData/reference/TISSUE_ABBREV.html. 

I did a couple iterations of rebuilding both sites after adding the URLs, so I think I'm missing something else. I'd appreciate your help!
