### ISSUE TITLE
Sidebar with multiple links and custom sections

### ISSUE THREAD

**Issue by telphick** [r-lib/pkgdown#2221]
Hi @maelle ,

This is in relation to a closed ticket: https://github.com/r-lib/pkgdown/issues/1946

Is it possible to have a few rows under custom? Currently tried this but no luck.
```
home:
  sidebar:
    structure: [custom, authors, dev]
    components:
      custom:
        - title: General Information
          - text: "[Repository1](link)"
          - text: "[Repository2](link)"
        - title: Dashboards
          text: "[Dashboard](link)"
```

Kind regards,
Tiana
