### ISSUE TITLE
add alternative text to YAML config example for author images

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2282]
https://pkgdown.r-lib.org/reference/build_home.html#yaml-config-authors

```yaml
authors:
  firstname lastname:
    href: "http://name-website.com"
    html: "<img src='https://website.com/name-picture.png' width=72 alt='Name Website'>"
```
