### ISSUE TITLE
Navbar icons left of search

### ISSUE THREAD

**Issue by john-ioannides** [r-lib/pkgdown#2320]
I have this code indicating that the back icon should be placed left of the search bar, but instead it's placed on the right.
```
navbar:
  structure:
    right: [goback, search, gogs]
  components:
    goback:
      icon: fa-arrow-left
      href: /..
      aria-label: RZPackageLibrary
  gogs:
        icon: fa-code
```

![image](https://github.com/r-lib/pkgdown/assets/58605878/b9841782-75d4-4005-a037-106381963d4b)
