### ISSUE TITLE
References: The `section-desc` class isn't being applied the description

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pkgdown#2352]
Using pkgdown's own site for a reprex, the Build section of the reference index includes a `desc`ription:

```yaml
reference:
- title: Build
  desc:  Build a complete site or one of its components.
```

But in [the rendered HTML](https://pkgdown.r-lib.org/reference/index.html#build), the `section-desc` class is being applied to an empty `<p>` tag, rather than the description.

```html
<div class="section level2">
  <h2 id="build">Build<a class="anchor" aria-label="anchor" href="#build"></a></h2>
  <p class="section-desc"></p>
  <p>Build a complete site or one of its components.</p>
</div>
```
