### ISSUE TITLE
Add pandoc css styling for `task-list`

### ISSUE THREAD

**Issue by jabenninghoff** [r-lib/pkgdown#2377]
From https://github.com/jgm/pandoc/issues/8151, pandoc uses CSS to render GitHub markdown [tasklists](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist).

pkgdown currently renders tasklists as bulleted lists with no space between the checkbox and the text. Importing the pandoc task-list styling from https://github.com/jgm/pandoc/blob/main/data/templates/styles.html to `pkgdown/extra.css` corrects this issue (contents below). Can the CSS below be added to the pkdown default CSS?

```css
/* pandoc task-list styling from https://github.com/jgm/pandoc/blob/main/data/templates/styles.html */
/* The extra [class] is a hack that increases specificity enough to
   override a similar rule in reveal.js */
ul.task-list[class]{list-style: none;}
ul.task-list li input[type="checkbox"] {
  font-size: inherit;
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}

```
