### ISSUE TITLE
Function name is not a valid topic name?

### ISSUE THREAD

**Issue by robmoss** [r-lib/pkgdown#2422]
I experience an error on GitLab CI, **but not locally**, where pkgdown 2.0.7 raises an error when building the function reference:

```text
! In '_pkgdown.yml', topic must be a known topic name or alias
✖ Not 'retic_steady_state'
```

where `retic_steady_state` is a documented and exported function in my package. The `reference` section of `_pkgdown.yaml` looks like:

```yaml
reference:
- title: "Model parameters"
  desc: >
    Functions that ...
  contents:
  - ends_with("_parameters")
  - retic_steady_state
```

In both cases, I'm calling `R -e 'pkgdown::build_site()'` from the command line, and the site builds without any issues on my laptop. I can't figure out why it behaves completely differently on GitLab CI — do you have any ideas? I can link to the CI job if that would be helpful.
