### ISSUE TITLE
FR: separate the customise vignette in 2: 1.theme your site and 2. customise navigation of your site

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2560]
As theming is different and only affects the `template:` part of the _pkgdown.yml file.

A lot of the customisation is pkgdown.Rmd, but possibly this vignette could be made shorter.

I am trying to put together a list of all fields accepted in `_pkgdown.yml` and try to document as much as possible in a single place, so that when you are trying to customize one part, you have a starting point that takes you to the correct place.

 Is there such a list already in the docs?

Here is what I found so far.
```yaml
intro:
navbar:
reference:
articles:
search:
lang:
home:
url:
destdir:
redirects:
navbar:
news:
template:
```

Also `check_pkgdown()` doesn't inform if it finds an unkown field and silently ignores it
