### ISSUE TITLE
non-syntaxic / link in  family name `has_concept()`

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2647]
Wondering if I am drifting too far away.

I have a set of related functions. I have created a help topic for those

help-main.

```r

#' @family [helper][help-main] functions
f1 <- function(x) {
}
#' @family [helper][help-main] functions
f2 <- function(x) {
}
```

I run `document()`,

In the .Rd file, I see

```rd
Other \link[=help-main]{helper} functions:  
```

In _pkgdown.yml

```yaml

reference:
  title: Functions
  contents: 
  - has_concept("\link[=help-main]{helper} functions")
```

TIL that you can use md links in `@family`, so naturally I thought: does pkgdown support that.
I just thought this was a cool pattern to add 

I am not sure what error I get

```r
# I got the non-valid R code one
! Topic must be valid R code, not
  "has_concept(\"\\link[=location-helper]{location helper} functions\")".

```

Or the can't find topics one!

This is probably not worth fixing, but thought I'd document what I found for future reference!
