### ISSUE TITLE
pkgdown 2.1.0 prevents `\eqn{}` and `\deqn{}` math rendering on function reference pages under Bootstrap 5

### ISSUE THREAD

**Issue by nanxstats** [r-lib/pkgdown#2704]
## Minimal reproducible example

```r
#' Example
#'
#' @param x \eqn{f(x) > 0}: inline equation
#'
#' @details
#' Display equation:
#'
#' \deqn{y = \alpha + \beta X + \varepsilon}
#'
#' @export
f <- function(x) NULL
```

and set

```yaml
template:
  bootstrap: 5
```

in `_pkgdown.yml`.

## pkgdown 2.1.0 + Bootstrap 5

<details><summary>Expand screenshot</summary>
<img width="847" alt="Screenshot 2024-07-08 at 4 17 57 PM" src="https://github.com/r-lib/pkgdown/assets/199363/f92c1eec-131a-4e26-a57c-fe5f0dc4b635">
</details>

## pkgdown 2.0.9 + Bootstrap 5

<details><summary>Expand screenshot</summary>
<img width="847" alt="Screenshot 2024-07-08 at 4 20 27 PM" src="https://github.com/r-lib/pkgdown/assets/199363/857cbe15-e9fd-4793-92e4-9bdb5d35d306">
</details>

**Comment by hadley** [comment]
Hmmm, I wonder what's different between your example and https://pkgdown.r-lib.org/articles/test/rendering.html#math

**Comment by cgiachalis** [comment]
@nanxstats Did you try to set to previous default, e.g. ` mathjax`. That's solve my problem at least.

```yaml
template:
  bootstrap: 5
  math-rendering: mathjax
```

**Comment by jayhesselberth** [comment]
Confirmed, setting `math-rendering: mathjax` fixes this issue.

We should try to figure out why mathml (which is now the default) doesn't work.

**Comment by cgiachalis** [comment]
Just to mention that the rendering is not what is used to be. I see different fonts as reported in #2739. 

Right clicking on the equation -> About MathJax, I get the following:

*Current version*
![Screenshot 2024-08-08 at 16-48-46 356247653-d3f2b46e-10](https://github.com/user-attachments/assets/45b78015-67a4-4914-9fe7-8c6e51730d35)

*Before v2.1.0*
![Screenshot 2024-08-08 at 16-42-06 Diversification Ratio](https://github.com/user-attachments/assets/cc9e714a-0fe4-4ff5-b14f-05e73645149e)

**Comment by cgiachalis** [comment]
And the answer is here:
https://docs.mathjax.org/en/latest/upgrading/v2.html#not-yet-ported-to-version-3

> The MathJax v3 output jax currently only support one font, the MathJax TeX fonts. Improved font support is an important goal for version 3, and this is one of the next features to be addressed. We will be rebuilding the fonts used for MathJax, and making additional web fonts available in a future release. We also plan to make the tools used for creating the necessary font data available for use in porting your own fonts for use with MathJax.

So by upgrading mathjax to v3.2.2, we don't get web text fonts..

**Comment by nanxstats** [comment]
This is how math rendering looks like using `math-rendering: "mathjax"` under pkgdown 2.1.0 (reproduced under both macOS and Windows):

<details><summary>Expand screenshot</summary>
<img width="833" alt="mathjax" src="https://github.com/user-attachments/assets/3298d682-b637-4949-b40f-14a61442a009">
</details>

Maybe it's because the MathJaX fonts are missing, from all the 404s in network requests:

<details><summary>Expand screenshot</summary>
<img width="920" alt="mathjax-fonts" src="https://github.com/user-attachments/assets/b9de6d36-3efc-4d03-8449-61d1abb11b1c">
</details>

----

Since it's tricky to side-load the MathJax fonts (originally defined in JS), my current workaround is to use the `katex` option and side-load the KaTeX fonts (also missing from pkgdown) using `pkgdown/extra.css`. Example: https://github.com/keaven/gsDesign/pull/161

I'm not a place to suggest anything on the font situation, but it would be very useful to have math rendering working again on function reference pages for all engine types.

**Comment by jayhesselberth** [comment]
@nanxstats Do you know if there is a CDN source for katex / Mathjax fonts? If so we could include them in the dependencies:

https://github.com/r-lib/pkgdown/blob/1d40a80e6b3564a6d7da0ce467b0a4570aa5665e/R/external-deps.R#L60-L91

We're probably not going to bundle math fonts in pkgdown itself.

**Comment by cgiachalis** [comment]
Indeed, `katex` option didn't  work either out of the box.

Thanks for confirming @nanxstats .

**Comment by jayhesselberth** [comment]
Would we expect inclusion of these [fonts](https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/output/chtml/fonts/tex.min.js
) from [cdnjs](https://cdnjs.com/libraries/mathjax) to have an effect? These could be added to the mathjax dependencies. There are also SVG fonts, not sure which we'd need.

**Comment by nanxstats** [comment]
@jayhesselberth I will let the MathJax experts comment on what should be used.

For KaTeX, I _think_ you can add these [60 fonts files](https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/fonts/) as "cached dependency" (may not look pretty...). It didn't work before probably because the CSS file is cached locally and distributed with the pkgdown site. It contains relative font paths that are interpreted as the pkgdown site instead of the CDN site.

**Comment by jayhesselberth** [comment]
If we're going to need to include many external font dependencies for katex / mathjax, we may need to go back to the yaml format that was originally in #2249.

**Comment by louisaslett** [comment]
I've hit this issue just now, and felt it was a bit much work to include all the font files manually although that was a cool solution given above.  My slightly hacky approach is just to remove the `math-rendering: katex` completely and inject the [official KaTeX starter template headers](https://katex.org/docs/browser#starter-template) directly, which uses the CDN for everything:

```yaml
template:
  bootstrap: 5
  includes:
    in_header: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
      <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script>
      <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>
```

I found this "just worked" for now thankfully, though it'd be really nice to have this fixed (ideally with option not to use CDN) so that the `math-rendering: katex` is all we need.
