### ISSUE TITLE
Tabset box heights are based upon largest tab

### ISSUE THREAD

**Issue by al-obrien** [r-lib/pkgdown#2721]
## The issue:

The height of the entire tab section is dependent upon the largest tab content, which can leave a lot of white space.

## Example
You can see this in the example from the pkgdown website.

![image](https://github.com/user-attachments/assets/692604ee-e45b-496b-9a53-66cb949e8438)

## Possible work around
I suspect this could be due to bootstrap itself, and I can work around it by forcing the CSS displays to another option.

```css
/* Correct flex boxes from sizing based upon the largest in tabset*/
.tab-content>.tab-pane {
  display: none;
}

.tab-content>.active {
  display: block;
}
```
