### ISSUE TITLE
Bug:  In dev site - The text on our Authors page about authors and contributors does not show anymore 

### ISSUE THREAD

**Issue by bms63** [r-lib/pkgdown#2788]
Hi all,

Love this package!!

We noticed in our dev version that the custom text we had in our Authors page has disappeared.   Any ideas?

Please see issue in admiral repo for additional context:
https://github.com/pharmaverse/admiral/issues/2511

**Comment by jayhesselberth** [comment]
For reference, this text is specified here:

https://github.com/pharmaverse/admiral/blob/dd42a6718bd8980d1e6974eb609398c74e3c39a5/_pkgdown.yml#L25-L31

``` yaml
authors:
  before: "We define *authors* as those who are actively maintaining the code base, and *contributors* as those who made a significant contribution in the past. For all acknowledgements, see the eponymous section in the [Home Page](https://pharmaverse.github.io/admiral/)."
  footer:
    roles: [aut, ctb, cre, fnd]
    text: "Developed by"
  sidebar:
    roles: [aut]
```
