### ISSUE TITLE
Static PDF/Rnw vignettes

### ISSUE THREAD

**Issue by SebKrantz** [r-lib/pkgdown#2870]
I have, in the {dfms} package on CRAN, a vignette called "dynamic_factor_models.Rnw", with content: 

```latex
\documentclass{article}
\usepackage{pdfpages}
%\VignetteIndexEntry{Dynamic Factor Models: A Very Short Introduction}
\begin{document}
\includepdf[pages=-, fitpaper=true]{dynamic_factor_models_paper.pdf}
\end{document}
```

In `_pkgdown.yml`, 

```yml

articles:
  - title: Introduction to dfms
    desc: Provides a walk-through of all main features
    contents:
    - introduction
  - title: Dynamic Factor Models - A Very Short Introduction
    desc: Provides a short theoretical overview of dynamics factor models as used in the economics literature
    contents:
    - dynamic_factor_models
```

Doesn't work. How can I include the Rnw or the PDF vignette (URL would suffice) on the site?
