### ISSUE TITLE
Use development version of pkgdown in GHA

### ISSUE THREAD

**Issue by petelaud** [r-lib/pkgdown#2876]
Sorry if this is the wrong place to ask, but is it possible to have GitHub Actions use the development (GitHub) version of pkgdown instead of the latest release?

**Comment by jayhesselberth** [comment]
Yes, I think you need to update this section in your GHA workflow, modifying the `extra-packages` field to reference the github repository (this would install the main branch).

```yaml
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: r-lib/pkgdown, local::.
          needs: website
```
