### ISSUE TITLE
How to disable checkboxes in the rendered home page?

### ISSUE THREAD

**Issue by jmgirard** [r-lib/pkgdown#2901]
I want to have a checkbox list on my README that gets posted on the home page, but I don't want the items to be interactive in HTML (i.e., I don't want the user to be able to click them to toggle them on or off).

Steps for MWE:
1. Open RStudio
2. File > New Project > New R Package
3. `usethis::use_readme_rmd()`
4. `usethis::use_pkgdown()`
5. Edit README.Rmd to contain:
````
---
output: github_document
---

- [ ] unfilled
- [x] filled
````
6. `devtools::build_readme()`
7. `pkgdown::build_site()`
8. Click on the checkboxes or list text to toggle them on/off

I tried adding CSS directly and via a .css file but am struggling to get this to be reflected in the HTML.
I believe the CSS is correct and this issue is more of how to get the CSS into that HTML file via pkgdown:

```css
ul.task-list input[type="checkbox"] {
  pointer-events: none;
  cursor: default;
  accent-color: gray;
}
ul.task-list label {
  pointer-events: none;
  cursor: default;
}
```
