### ISSUE TITLE
Two levels of nesting in reference index 

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#327]
For very long reference indexes (like [keras](https://keras.rstudio.com/reference/index.html)). Ideally toc would expand/contract too. Could also imagine having a separate page for each top level section.

**Comment by hadley** [comment]
Could also imagine having a separate page for each top level section

**Comment by hadley** [comment]
rlang also needs it: http://rlang.r-lib.org/reference/index.html

**Comment by hadley** [comment]
@jayhesselberth this seems like it might be worth revisiting now that we have a better TOC in the sidebar.

**Comment by jayhesselberth** [comment]
For [keras](https://github.com/rstudio/keras/blob/09de409ece8b9a47a4f915ee7397c486fc1e9e91/pkgdown/_pkgdown.yml#L76), a second natural level could be for "Layers". Easiest way to implement would be to add a "group" section and nest titles under that. Groups would be assigned h2 and titles would get h3.

``` yaml
reference:
  - group: "Layers"
    - title: "Core Layers"
      contents:
      - layer_input
    ...
    - title: "Convolutional Layers"
      contents:
      - starts_with("layer_conv_")
    ...
```
Need to think about how this would work if no groups were specified, or if there were a mixture of groups with titles and just bare titles not associated with a group.

**Comment by hadley** [comment]
Maybe we could say that `contents` could also be a richer list?

```yaml
reference:
- title: "Layers"
  contents:
  - title: "Core Layers"
    contents:
    - layer_input
    ...
  - title: "Convolutional Layers"
    contents:
    - starts_with("layer_conv_")
...
```

**Comment by hadley** [comment]
That would be a bit easier to work with if we used something other than `title` at the top-level:

```yaml
reference:
- section: "Layers"
  contents:
  - title: "Core Layers"
    contents:
    - layer_input
    ...
  - title: "Convolutional Layers"
    contents:
    - starts_with("layer_conv_")
...
```

Then `reference` is always a list and each child must have either a `section` or a `title` element.

**Comment by hadley** [comment]
Or maybe make the special name go inside?

```R
reference:
- title: "Layers"
  contents:
  - subtitle: "Core Layers"
    contents:
    - layer_input
    ...
  - subtitle: "Convolutional Layers"
    contents:
    - starts_with("layer_conv_")
...
```

Then `title` is always `<h2>` and `subtitle` is always `<h3>`

**Comment by jayhesselberth** [comment]
Another idea would be to enable a user-provided TOC spec for a section. Would create the TOC by parsing the initial html output, updating `h2` (matching by `title`) and `h3` (matching by `subtitle`) with `data-toc-text` values from the spec.

In this case we wouldn't have to rewrite reference processing code and the TOC spec might also be useful for articles.

``` yaml
reference:
  toc:
  - title: "Layers"
    subtitle: "Core Layers"
    subtitle: "Convolutional Layers"

 ... original reference is unchanged ...

  - title: "Core Layers"
    contents:
    - layer_input
    ...
  - title: "Convolutional Layers"
    contents:
    - starts_with("layer_conv_")
    ...
```

**Comment by hadley** [comment]
My main concern with that approach is the matching is a bit tricky, and we'd have to think carefully about messaging so people could figure out why things were going wrong. Anyway, I'll have a play around over the next couple of days, and see how it feels with an implementation.

**Comment by hadley** [comment]
Yet another idea — we could flatten the yaml:

```yaml
reference:
- title: "Layers"
- subtitle: "Core Layers"
- topics:
  - layer_input
- subtitle: "Convolutional Layers"
- topics:
  - starts_with("layer_conv_")
```

This would be a bigger change, but I think I'm going to do it internally because it makes the implementation simpler.

**Comment by hadley** [comment]
For now, I think we can leave at

```yaml
reference:
- title: "Layers"
- subtitle: "Core Layers"
  contents:
  - layer_input
- subtitle: "Convolutional Layers"
  contents:
  - starts_with("layer_conv_")
```
