### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by GegznaV** [r-lib/pkgdown#379]
How is it possible to add a favicon to my `pkgdown ` site automatically? E.g., through YALM settings.

**Comment by lbusett** [comment]
Hi, 

   to add a favicon in one of the entries of the top menu, you just specify an attribute "icon" for an entry of the navbar in the "_pkgdown.yaml" file in the root of your package. 

For example: 

```
title: mypackage
template:
  params:
    bootswatch: flatly
reference:
  - title: Exported Functions
    desc: ~
    contents:
      - '`aaaa`'
      - '`bbbb`'
navbar:
  type: inverse
  left:
    - icon: fa-home
      href: index.html
    - text: "faq"
      icon: fa-question-circle-o
      href: articles/faq.html
```
would give you an entry "home" in the navbar with just an icon, and an entry "faq" with both icon and text pointing to "faq.html"
As per `build_site` documentation, the list of icons can be found here: 
http://fontawesome.io/icons/

You can also put favicons wherever you want in the text of the Rmd, by inserting in this case the "full html specification" of the favicon (instead than only its name). For example:

`I want a <i class="fa fa-github" aria-hidden="true"></i> icon   `

would render in the website with a "github" icon. 

HTH
