### ISSUE TITLE
learnr integration

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#455]
User will responsible for publishing tutorials. pkgdown will automatically discover if stored in `inst/tutorials`, and rsconnect has been used to publish (using `rsconnect::deployments()`). Otherwise the user will need to popular a new top-level entry in `_pkgdown.yml:`

```yaml
tutorials
-  url: https://hadley.shinyapps.io/mytutorial
   title: A really great tutorial
   source: Optionally, a link to the source on GitHub
```

Each tutorial will get an entry in a new top-level nav ("Tutorials"), and will get a file in `tutorials/` that uses an appropriately styled iframe to embed the tutorial within the pkgdown template. The footer should include a link to learnr so people can learn more about it.

We'll also need to make sure it's easy/cheap for people to host learnr tutorials in their personal shinyapps accounts.
