### ISSUE TITLE
Standard way of linking to release announcements

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#550]
e.g. http://usethis.r-lib.org/index.html

Maybe 

```
news:
  releases:
  - title: usethis 1.1.0
    href: https://www.tidyverse.org/articles/2017/11/usethis-1.0.0/
```
