### ISSUE TITLE
How do you get the RStudio logo into your authors section?

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/pkgdown#712]
Hi,

Been looking through the documentation and of the PkgDown code itself.

How did you render the RStudio logo in the right hand side of the page? I'd quite like to get our institution logos onto my package documentation as I flesh it out.

Also - could this info be added to the pkgdown documentation guides?

**Comment by jayhesselberth** [comment]
The R Studio logo is added [internally to the authors data](https://github.com/r-lib/pkgdown/blob/fb68cf8f323e86efb5998b93d5c51a70b674e6c3/R/build-home-authors.R#L40-L43) if it is present in the [`DESCRIPTION`](https://github.com/r-lib/pkgdown/blob/master/DESCRIPTION#L11).

You can do the same with your `DESCRIPTION`:

```
# authors with aut, cph, or fnd types are add to home page
person("institution", role = c("cph", "fnd"))
```

and your `_pkgdown.yml`:

```yaml
authors:
  institution:
    href: "http://institution.com"
    html: "<img src='institution.png'>"
```

Will add a blurb to the docs.
