### ISSUE TITLE
Multiline reference->desc string

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/pkgdown#713]
Hi,

Building on my previously linked package output, I've just been trying to configure the reference page
up:

```
reference:
  - title: Load
    desc:  Load a SSNAP CSV file.
    contents:
    - ssnapcsv
  - title: Bitfields
    desc: Groups of booleans are stored for efficiency as single numbers. Each bit for each field is named in these vectors.
    contents:
    - tPANoBut
    - tPAComplications

```

If I split the desc line over multiple lines, this throws a parsing error up.

Error in yaml.load(readLines(con), error.label = error.label, ...) : 
  (./_pkgdown.yml) Scanner error: while scanning a simple key at line 34, column 3 could not find expected ':' at line 35, column 3
Calls: withCallingHandlers ... <Anonymous> -> yaml.load -> .handleSimpleError -> h

Checking elsewhere, multiple line strings should be OK:
https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines

Is this something the code isn't designed to handle at present? Or is pkgdown expecting a syntax that I'm missing?

**Comment by jayhesselberth** [comment]
Mark sections with long lines using `>`:

```yaml
  - title: Bitfields
    desc: >
      Groups of booleans are stored for efficiency as single numbers.
      Each bit for each field is named in these vectors.
    contents:
    - tPANoBut
    - tPAComplications
```

https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines

**Comment by md0u80c9** [comment]
Interesting - just tried this and no joy:

Copied and pasted the exact string below:

```
reference:
  - title: Load
    desc:  Load a SSNAP CSV file.
    contents:
    - ssnapcsv
  - title: Bitfields
    desc: >
    Groups of booleans are stored for efficiency as single numbers.
    Each bit for each field is named in these vectors.
    contents:
    - tPANoBut
    - tPAComplications

```

> pkgdown::build_site()
Error in yaml.load(readLines(con), error.label = error.label, ...) : 
  (./_pkgdown.yml) Scanner error: while scanning a simple key at line 26, column 5 could not find expected ':' at line 27, column 5
Calls: withCallingHandlers ... <Anonymous> -> yaml.load -> .handleSimpleError -> h
Execution halted
Error in yaml.load(readLines(con), error.label = error.label, ...) : 
  (./_pkgdown.yml) Scanner error: while scanning a simple key at line 26, column 5 could not find expected ':' at line 27, column 5
>
