### ISSUE TITLE
pkgdown 1.1.0 does not process \doi tags

### ISSUE THREAD

**Issue by strengejacke** [r-lib/pkgdown#720]
When I use `build_site()` with my package (https://github.com/strengejacke/sjstats), I get following error for _pkgdown 1.1.0_:

> Reading 'man/deff.Rd'
> Error: `x` must be a string or a R connection
> Execution halted

Reverting to pkgdown 1.0.0 solves the problem, there's no error then.

**Comment by jayhesselberth** [comment]
I get a clean build using pkgdown master with your most recent commit.

https://vigorous-fermi-749ebd.netlify.com/

```yaml
pandoc: 2.2.1
pkgdown: 1.1.0.9000
pkgdown_sha: ~
articles:
  anova-statistics: anova-statistics.html
  bayesian-statistics: bayesian-statistics.html
  mixedmodels-statistics: mixedmodels-statistics.html
```
