### ISSUE TITLE
Add github SHA info to site metadata

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#721]
Add the commit SHA of the version of the package being built to package metadata so its easy to tell the repo state the docs were build from.

```
pandoc: 2.2.1
pkgdown: 1.1.0.9000
pkgdown_sha: ~
package_sha: XXX
articles:
  anova-statistics: anova-statistics.html
  bayesian-statistics: bayesian-statistics.html
  mixedmodels-statistics: mixedmodels-statistics.html
```
