### ISSUE TITLE
yaml to set project link?

### ISSUE THREAD

**Issue by arilamstein** [r-lib/pkgdown#756]
First of all: thank you to everyone who has worked on pkgdown! I am just started to use it and really love it.

I am trying to incorporate a portion of the output of pkgdown into my website. I have a page that lists my various R packages, and I want to add a button where users can see the pkgdown /reference/index.html for each package.

This is working fine, except one thing. On /reference/index.html, the package name appears in the upper-left. And when I click on it, it takes me to the pkgdown home. I would like to override that link so that clicking the package name takes me to /reference/index.html. Is that possible?

Is this possible? Here is a screenshot of what I mean.

<img width="894" alt="pkgdown" src="https://user-images.githubusercontent.com/50784/42294544-9f9845be-7f96-11e8-8776-cde3a435bcc0.png">

Also, here is the _pkgdown.yml I am using:
```
navbar:
  title: ~
  type: default
  left:
  - text: Home
    href: https://www.arilamstein.com
  - text: Open Source
    href: https://arilamstein.com/open-source/
  - text: Courses
    href: https://courses.arilamstein.com/
  - text: Corporate Services
    href: https://arilamstein.com/corporate-services/
```
