### ISSUE TITLE
Select topics by concept

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#758]
Based on discussion in #755 

`template_reference(concepts = TRUE)` could automatically generate:

```yaml
reference:
- title: Concepts
  contents:
  - has_concept("this")
  - has_concept("that")
- title: Other
  contents:
  - other
```

Need dev changes from roxygen2.
