### ISSUE TITLE
custom docmentation url of other packages

### ISSUE THREAD

**Issue by dongzhuoer** [r-lib/pkgdown#765]
Currently, links to the documentation of functions in other package are implemented by www.rdocumentation.org, for example, `devtools::install_github()` in linked to http://www.rdocumentation.org/packages/devtools/topics/install_github

But some packages are not archived by www.rdocumentation.org. What about add an option like

```yaml
documentation:
  pkgdown:
    pkg: https://user.github.io/pkg
```

to specify that `pkg::foobar` should be linked to https://user.github.io/pkg/reference/foobar.html. (In the above example, `pkgdown:` means the documentation site is built by pkgdown, it tells how to generate url for specific function and enables future extensibility)

**Comment by dongzhuoer** [comment]
Or the option may be

```yml
documentation:
  pkgdown:
    rule: https://user.github.io/@pkg_name/reference/@fun_name.html
   packages: [pkg1, pkg2]
```
