### ISSUE TITLE
Section numbering missing in vignette

### ISSUE THREAD

**Issue by aravind-j** [r-lib/pkgdown#857]
In case of vignette Rmd files rendering to `pdf_document` or `html_document` with `numbered sections: yes`, the section numbers are not rendered by `build_articles`.

YAML header

```
output:
  html_document:
    number_sections: yes
    toc: yes
```

```
output:
  pdf_document:
    number_sections: yes
    toc: yes
```
