### ISSUE TITLE
Distinguish local and remote links with a class

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#881]
And then style so that you can tell when you're going to a remote link.

**Comment by Bisaloo** [comment]
What about:

```css
a[href^="http"] {
  color: green;
}
```

![screenshot from 2018-11-25 16-19-22](https://user-images.githubusercontent.com/10783929/48980813-233e1300-f0ce-11e8-90c9-c38c6e9ece3c.png)

----

or possibly even better (with the pkg URL instead of `https://pkgdown.r-lib.org/` of course):

```css
a[href^="http"]:not([href^="https://pkgdown.r-lib.org"]) {
  color: green;
}
```

![screenshot from 2018-11-25 16-20-32](https://user-images.githubusercontent.com/10783929/48980811-233e1300-f0ce-11e8-96ba-2506db24ea19.png)

----

If you want this to only happen to links to function documentation:

```css
code a[href^="http"]:not([href^="https://pkgdown.r-lib.org"]) {
  color: red;
}
```

![screenshot from 2018-11-25 16-31-12](https://user-images.githubusercontent.com/10783929/48980929-9431fa80-f0cf-11e8-929d-440d4e7fd4fc.png)

It still requires a bit more tweaking because it looks like R classes can be linked without being in a `<code></code>` environment.

Let me know if you would like me to submit a PR!

----

On a related note, it seems strange that some local links use absolute instead of relative url (e.g. `pkgdown::build_site()` in the code line). This means a new connection has to be initiated when the user clicks on it.

**Comment by Bisaloo** [comment]
Or maybe in your case,

```css
a[href^="https://rdocumentation.org/"] {
  color: green;
}
```

might be enough
