### ISSUE TITLE
Hide sidebar on mobile homepage

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#913]
```css
/* hide sidebar on mobile devices */
@media (max-width: 767px) {
  #sidebar {
    display: none;
  }
}
```
