### ISSUE TITLE
make it more clear how to cross link to other pkgdown site

### ISSUE THREAD

**Issue by dongzhuoer** [r-lib/pkgdown#946]
I'm very happy to see that link to other package can be customized, rather than just use www.rdocumentation.org .

However, the [document](https://github.com/r-lib/pkgdown/issues/765#issuecomment-449702551) is too simple, I have spent a while finding how to achieve this.

**Comment by dongzhuoer** [comment]
For an example, for this sentence in ["Programming with dplyr"](https://dplyr.tidyverse.org/articles/programming.html) vignette of dplyr

If this function is in a package, using `.data` also prevents `R CMD check` from
giving a NOTE about undefined global variables (provided that you've also
imported `rlang::.data` with `@importFrom rlang .data`).

**Comment by dongzhuoer** [comment]
This is achieved in 

1. https://github.com/r-lib/rlang/blob/e7475ab5d8e0012300a86f8b0e7f2268d7d1f46a/DESCRIPTION#L28

**Comment by dongzhuoer** [comment]
then pkgdown try each url, and finds the `https://rlang.r-lib.org/pkgdown.yml` does exist:

```yaml
pandoc: '2.2'
pkgdown: 1.3.0.9000
pkgdown_sha: fa9b7502e80401db4b410086b0a8f6ab444f0c66
articles: []
urls:
  reference: https://rlang.r-lib.org/reference
  article: https://rlang.r-lib.org/articles
```
