### ISSUE TITLE
Update Font Awesome library

### ISSUE THREAD

**Issue by msberends** [r-lib/pkgdown#953]
Please update the Font Awesome library, I now have to look for the 4.7 reference, while Font Awesome 5 is out already. I first wondered why for example this wouldn't work in my `navbar`:

```yml
    - text: 'Manual'
      icon: fa-book-open
      href: 'reference/'
```

The reason appeared to be that `fa-book-open` is not available in older Font Awesome libraries.

Please update it, and replace the `fa` class with `fas` in your CSS classes as described here: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use.

Thanks!
