### ISSUE TITLE
Select topics by family

### ISSUE THREAD

**Issue by grabear** [r-lib/pkgdown#954]
Hello pkgdown!

I'm working on a package and we've started our `pkgdown `documentation.  I was wondering if there was a way to utilize the roxygen tag `@family` to create reference sections in the pkgdown.yml file?  If not then this is a feature request!  I was envisioning something like:
```yaml
reference:
- title: Data Visualization
  contents:
  - with_family("Data Visualization")
  # OR
  - family("Data Visualization")
```

Regardless thanks for all your hard work.  pkgdown has been super useful for us and our projects. 😃 
Cheers,
@grabear
