### ISSUE TITLE
Including functions with similar rd/man pages in references 

### ISSUE THREAD

**Issue by Blackglade** [r-lib/pkgdown#986]
Currently I am specifying the types of functions to use with my _pkgdown.yaml config file. Several functions in a library I'm working on have the same man page generated by roxygen2. I however want to include these functions in separate categories on the references page. For example, given the following functions:

```
#' @rdname foo_bar
foo <- function(){}

#' @rdname foo_bar
bar <- function(){}
```
Specifying my yaml config file like this:
```
reference:
- title: Group A
  contents:
  - foo
- title: Group B
  contents:
  - bar
```
 yields two separate sections... but BOTH sections include the foo() and bar() function despite individually defining them only because they are linking to the same man/rd page
