### ISSUE TITLE
Incorrect highlighting of active navigation category

### ISSUE THREAD

**Issue by gustavdelius** [r-lib/pkgdown#992]
There is a problem with the algorithm that determines which navbar item to highlight, introduced in #699 in an attempt to fix #660. If one uses the article index page to link to the articles, then when an article is opened, the "Get started" navbar item is highlighted instead of the "Articles" item. The following _pkgdown.yml illustrates this:
```
navbar:
  structure:
    left: [home, intro, reference, articles, news]
    right: [github]
  components:
    articles:
      text: Articles
      href: articles/index.html

articles:
  - title: "Testing"
    contents:
    - test
```
The confusion arises because both "Get started" and "Articles" point to a page in the articles subdirectory.
