### ISSUE TITLE
Order of vignettes in articles section dropdown menu

### ISSUE THREAD

**Issue by ddiez** [r-lib/pkgdown#995]
I am trying to set the order of vignettes in the Articles' section of the navbar without success. Here is a minimal repository that highlights the problem: https://github.com/ddiez/foo

There are two vignettes: analysis-1 and introduction. They are rendered in alphabetical order in the dropdown menu. I would like to have the introduction vignette first. For this I set the following options in `_pkgdown.yml`:

```
navbar:
  structure:
    left:
    - home
    - intro
    - reference
    - articles
    - tutorials
    - news
    right: github
  components:
    home:
      icon: fa-home fa-lg
      href: index.html
    reference:
      text: Reference
      href: reference/index.html
    articles:
      text: Articles
      menu:
      - text: Introduction
        href: articles/introduction.html
      - text: Analysis 1
        href: articles/analysis-1.html
```

I know this file is being read by pkgdown because if I change the name of the Articles section to some other name the change is reflected. For example, changing the name of the articles section from Articles to Articles2 as below:

```
 articles:
      text: Articles2
      menu:
      - text: Introduction
        href: articles/introduction.html
      - text: Analysis 1
        href: articles/analysis-1.html
```

But any changes in the name or the order of the entries in the menu part of the articles section are apparently ignored. I am assuming it's a bug but it may be also that I am missing something. Any help on this will be appreciated.

**Comment by ddiez** [comment]
OK this is embarrassing. After expending several hours over a few days struggling with this I have found a solution after submitting this issue. The realization came after cloning the pkgdown package and looking at its vignette section. Basically I can give the vignette files any name I want. So changing the names to e.g. `01_introduction.md` and `02_analysis-1.md` with put them in the desired order. The name in the dropdown menu will be anyway the one defined inside the vignette.

**Comment by ddiez** [comment]
I found that `R CMD check` complains about using invalid file names (i.e. starting with a number). So the solution is to use some letter like `a01_introduction.md` and `a02_analysis-1.md`.

**Comment by nsgrantham** [comment]
You may not have to rename your files this way.

The following in `_pkgdown.yml` should work:
```
articles:
- title: Articles
  navbar: ~
  contents:
  - introduction
  - analysis-1
```

More on how this works at https://pkgdown.r-lib.org/reference/build_articles.html
